"""align schema with models

Make organizations.organization_code unique and drop the
legacy user_roles.id / assigned_at columns plus the redundant
unique constraint, returning user_roles to the association
table shape declared in the User model.

Revision ID: 44c7742f9251
Revises: 88256b642540
Create Date: 2026-08-08 09:46:17.051605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c7742f9251'
down_revision: Union[str, Sequence[str], None] = '88256b642540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    with op.batch_alter_table('user_roles') as batch_op:
        batch_op.drop_constraint(
            'uq_user_roles_user_role',
            type_='unique',
        )
        if bind.dialect.name == "postgresql":
            batch_op.drop_constraint(
                'user_roles_pkey',
                type_='primary',
            )
        batch_op.create_primary_key(
            'user_roles_pkey',
            ['user_id', 'role_id'],
        )
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('id')

    op.drop_index(op.f('ix_organizations_organization_code'), table_name='organizations')
    op.create_index(op.f('ix_organizations_organization_code'), 'organizations', ['organization_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    with op.batch_alter_table('user_roles') as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(
            sa.Column(
                'assigned_at',
                sa.DATETIME(),
                server_default=sa.text('CURRENT_TIMESTAMP'),
                nullable=False,
            ),
        )
        batch_op.create_unique_constraint(
            op.f('uq_user_roles_user_role'),
            ['user_id', 'role_id'],
        )
        if bind.dialect.name == "postgresql":
            batch_op.drop_constraint(
                'user_roles_pkey',
                type_='primary',
            )
        batch_op.create_primary_key(
            'user_roles_pkey',
            ['id'],
        )

    op.drop_index(op.f('ix_organizations_organization_code'), table_name='organizations')
    op.create_index(op.f('ix_organizations_organization_code'), 'organizations', ['organization_code'], unique=False)
    # ### end Alembic commands ###
