"""align users table with models

Drop the redundant users_email_key unique constraint
(email uniqueness is enforced by the ix_users_email unique index).

Revision ID: 4ad4d2a2e737
Revises: a1b2c3d4e5f6
Create Date: 2026-08-02 17:45:56.166709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad4d2a2e737'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    names = [
        c["name"]
        for c in sa.inspect(bind).get_unique_constraints("users")
    ]

    if "users_email_key" in names:
        with op.batch_alter_table('users') as batch_op:
            batch_op.drop_constraint('users_email_key', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.create_unique_constraint('users_email_key', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
