from enum import Enum


class InventoryMovementType:

    STOCK_IN = "STOCK_IN"

    STOCK_OUT = "STOCK_OUT"

    ADJUSTMENT_IN = "ADJUSTMENT_IN"

    ADJUSTMENT_OUT = "ADJUSTMENT_OUT"

    TRANSFER_IN = "TRANSFER_IN"

    TRANSFER_OUT = "TRANSFER_OUT"

    PURCHASE = "PURCHASE"

    SALE = "SALE"

    RETURN_IN = "RETURN_IN"

    RETURN_OUT = "RETURN_OUT"


class InventoryStatus(str, Enum):

    OUT_OF_STOCK = "OUT_OF_STOCK"

    LOW_STOCK = "LOW_STOCK"

    HEALTHY = "HEALTHY"

    OVERSTOCKED = "OVERSTOCKED"