class InventoryMovementType:

    STOCK_IN = "STOCK_IN"

    STOCK_OUT = "STOCK_OUT"

    ADJUSTMENT_IN = "ADJUSTMENT_IN"

    ADJUSTMENT_OUT = "ADJUSTMENT_OUT"

    TRANSFER_IN = "TRANSFER_IN"

    TRANSFER_OUT = "TRANSFER_OUT"

    PURCHASE = "PURCHASE"

    SALE = "SALE"

    RETURN_IN = "RETURN_IN"

    RETURN_OUT = "RETURN_OUT"